trigger: none

name: Deploy Bicep Production

parameters:
  - name: serviceName
    type: string
    default: apc
    values:
      - apc
      - ji

  - name: deploy_prod
    displayName: Deploy to PROD
    type: boolean
    default: false

  # - name: deploy_shared
  #   displayName: Deploy Shared Resources (always true for test)
  #   type: boolean
  #   default: false

variables:
  vmImageName: "ubuntu-latest"
  subscriptionId: $(subscriptionId)

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    displayName: Build and Test
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureCLI@2
            displayName: 🧪 Test ${{parameters.serviceName}} infrastructure
            inputs:
              azureSubscription: defaultAzureServiceConnection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az upgrade
                az --version
                tags='{"BUSINESS-AREA":"SPT","RUNTIME-ENVIRONMENT":"test"}'
                az deployment sub create --what-if -f ./actions/bicep/Services/Common/infra.bicep --location westeurope --parameters serviceName=${{parameters.serviceName}} subscriptionId=$(subscriptionId) tags=$tags
  - stage: Deploy
    displayName: Deploy
    condition: |
      and(
        succeeded('Build'),
        eq(${{ parameters.deploy_prod }}, true)
      )
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureCLI@2
            displayName: 🏗 Deploy ${{parameters.serviceName}} infrastructure
            inputs:
              azureSubscription: defaultAzureServiceConnection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az upgrade
                az --version
                tags='{"BUSINESS-AREA":"SPT","RUNTIME-ENVIRONMENT":"test"}'
                az deployment sub create --what-if -f ./actions/bicep/Services/Common/infra.bicep --location westeurope --parameters serviceName=${{parameters.serviceName}} subscriptionId=$(subscriptionId) tags=$tags
